# Base configuration for MAS Orchestrator
# Common defaults shared across all experiments

# Model configuration
model:
  provider: "openai"  # openai, anthropic, groq
  name: "gpt-5-mini"
  # Note: GPT-5 does not support temperature parameter
  # Using default reasoning_effort and verbosity settings
  max_tokens: 4096
  timeout: 120

# Agent configuration
agents:
  max_agents: 10  # Maximum sub-agents constraint
  max_steps: 100
  max_tool_calls_per_turn: 5
  retry_policy: 1
  timeout_seconds: 300
  
# Planner configuration
planner:
  style: "adaptive"  # Let orchestrator decide decomposition approach
  determinism:
    seed: 42
    record_warnings: true

# Tools configuration
tools:
  code_interpreter:
    enabled: true
    timeout: 300
    description: "Python code execution environment for logical reasoning, calculations, data analysis, and problem-solving"
  disable_builtin_tools: true  # Disable OpenAI/Anthropic native tools by default
  
# RAG configuration (disabled by default, enabled for RAG experiments)
retrieval:
  enabled: false  # Start with non-RAG setup
  policy: "planning-only"  # or "planning+execution"
  top_k: 5
  max_retrievals_per_turn: 2
  rerank: false

# Telemetry and logging
telemetry:
  enabled: true
  log_level: "INFO"
  structured_logs: true
  trace_spans: false
  
# REALM-Bench integration
realm_bench:
  scenarios: ["P1", "P4", "P7", "P11"]  # Default test scenarios
  seeds: [42, 43, 44, 45, 46]  # 5 runs per scenario
  timeout_per_scenario: 300  # 5 minutes per scenario

# Evaluation settings
evaluation:
  metrics:
    planning_quality: 0.3
    planning_optimality: 0.3
    coordination_effectiveness: 0.2
    constraint_satisfaction: 0.2
  output_format: "json"
  save_artifacts: true